[theme]
font = "Nunito:https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap"
headingFontWeights = 800

[theme.light]
primaryColor = "#fb923c"
orangeColor = "#fb923c"
orangeTextColor = "#fb923c"

[theme.dark]
primaryColor = "#fb923c"
orangeColor = "#fb923c"
orangeTextColor = "#fb923c"
